{
    'name': 'Sale Partner Contractors',
    'version': '18.0.1.0.0',
    'summary': 'Manage contractors & sites under Contacts and add contractor/site to Sale Orders',
    'description_file': 'static/description/description.html',
    'author': 'Aspire Analytica',
    'website': 'https://aspireanalytica.com',
    'depends': ['base', 'sale', 'contacts'],
    'license': 'LGPL-3',
    'data': [
        'security/ir.model.access.csv',
        'views/partner_views.xml',
        'views/contractor_views.xml',
        'views/site_views.xml',
        'views/sale_order_views.xml',
    ],
    'images': ['static/description/icon.png',
               'static/description/cover.png'],
    'installable': True,
    'application': True,
    'auto_install': False,
    'price': 5.0,
    'currency': 'USD',
}